apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

images:
  - name: shipforge-product-service
    newName: 289984444209.dkr.ecr.ap-south-1.amazonaws.com/shipforge/product-service
    newTag: "14"

  - name: shipforge-order-service
    newName: 289984444209.dkr.ecr.ap-south-1.amazonaws.com/shipforge/order-service
    newTag: "14"
